### ISSUE TITLE
Connect Chiadog over SSH to the FULL_NODE

### ISSUE THREAD

**Issue by ebeng** [martomi/chiadog#144]
Hi all,

It is not totally a bug, but I cant find my way around to pass the password when I login to another machine over SSH. 
```
network_log_consumer:
    enable: true
    remoteuser: "xx"
```

I do get the following error back. 

```
[2021-05-18 20:34:20] [    INFO] --- Connected (version 2.0, client OpenSSH_8.2p1) (transport.py:1819)
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    log_consumer = create_log_consumer_from_config(chia_logs_config)
  File "/home/nfsserver/chiadog/src/chia_log/log_consumer.py", line 179, in create_log_consumer_from_config
    platform, path = get_host_info(
  File "/home/nfsserver/chiadog/src/chia_log/log_consumer.py", line 132, in get_host_info
    client.connect(hostname=host, username=user, port=port)
  File "/home/nfsserver/chiadog/venv/lib/python3.8/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/home/nfsserver/chiadog/venv/lib/python3.8/site-packages/paramiko/client.py", line 765, in _auth
    raise SSHException("No authentication methods available")
paramiko.ssh_exception.SSHException: No authentication methods available
```

What is the safest way ? To provide the password during the initialization of the script or work with SSH-keys (but how)?

**Environment:**
 - OS: Ubuntu Server 20.04 LTS
 - Python version: 3.8.5
 - PIP version: 21.1.1
 - Chia version: 1.1.5

**Comment by ebeng** [comment]
nvm:

http://www.linuxproblem.org/art_9.html

fixed with 2 commands....

**Comment by martomi** [comment]
The wiki page on [Monitoring Multiple Harvesters](https://github.com/martomi/chiadog/wiki/Monitoring-Multiple-Harvesters) describes this in more detail as well.
