### ISSUE TITLE
ImportError: attempted relative import beyond top-level package - Windows 10

### ISSUE THREAD

**Issue by HououinKyouma01** [martomi/chiadog#247]
**Describe the bug**

```
(venv) PS C:\Users\Farma\chiadog> .\start.cmd
Traceback (most recent call last):
  File "C:\Users\Farma\chiadog\main.py", line 12, in <module>
    from src.chia_log.handlers.daily_stats.stats_manager import StatsManager
  File "C:\Users\Farma\chiadog\src\__init__.py", line 5, in <module>
    from ...parsers.finished_signage_point_parser import FinishedSignagePointMessage
ImportError: attempted relative import beyond top-level package
(venv) PS C:\Users\Farma\chiadog>

```
Tried without venv too. All requirements installed. Config checked few times. 
Tried starting with
python.exe main.py --config 'C:\Users\Farma\chiadog\config.yaml'
python.exe main.py --config config.yaml

Same error.
**Environment:**
 - OS: Windows 10
 - Python version: 3.9
 - PIP version: 21.1.3
 - Chia version: 1.1.7

**Comment by pieterhelsen** [comment]
Try a full reinstall of git repo? 
It's trying to go up three folders from `src/__init__.py` which is not possible. 
It seems your install got corrupted somehow.

**Comment by martomi** [comment]
Agree with @pieterhelsen's suggestion. Closing for inactivity.
