### ISSUE TITLE
Dateutil module not working. 

### ISSUE THREAD

**Issue by BeepBo0** [martomi/chiadog#332]
Hi y'all. Been trying to get this sorted on my offtime but have officially run out of ideas. No matter what I try the dateutil module just doesn't work. I have tried this both on Windows10 and Windows Server 2019 with similar results. I am now throwing myself at the mercy of someone smarter than me. 

Having followed the listed guide exactly on both systems, I can never get the module to work within the script.

> PS C:\Users\Administrator\Documents\ChiaDog> pip install python-dateutil
> Requirement already satisfied: python-dateutil in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (2.8.2)
> Requirement already satisfied: six>=1.5 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil) (1.16.0)
> 
> PS C:\Users\Administrator\Documents\ChiaDog> pip check python-dateutil
> No broken requirements found.
> 
> PS C:\Users\Administrator\Documents\ChiaDog> .\start.cmd
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Documents\ChiaDog\main.py", line 12, in <module>
>     from src.chia_log.handlers.daily_stats.stats_manager import StatsManager
>   File "C:\Users\Administrator\Documents\ChiaDog\src\chia_log\handlers\__init__.py", line 14, in <module>
>     from .daily_stats.stats_manager import StatsManager
>   File "C:\Users\Administrator\Documents\ChiaDog\src\chia_log\handlers\daily_stats\__init__.py", line 5, in <module>
>     from ...parsers.finished_signage_point_parser import FinishedSignagePointMessage
>   File "C:\Users\Administrator\Documents\ChiaDog\src\chia_log\parsers\finished_signage_point_parser.py", line 9, in <module>
>     from dateutil import parser as dateutil_parser
> ModuleNotFoundError: No module named 'dateutil'

What am I doing wrong?

**Environment:**
 - OS: Windows Server 2019
 - Python version: 3.10
 - PIP version: 22.0.4
 - Chia version: 1.3
 - Chiadog version: 
 - Harvester: local

**Comment by pieterhelsen** [comment]
I assume you've found what was wrong? :)

Just for the sake of anyone stumbling onto this thread. The problem was likely that you were installing the dateutils package in your global python environment, but `chiadog` runs in a `venv`, a virtual environment or a sandbox, which does not have access to the globally installed packages. 

Make sure to follow the steps on https://github.com/martomi/chiadog/blob/main/WINDOWS.md#11-powershellnative-installation especially step 3. which installs and enabled the `venv`.

**Comment by pieterhelsen** [comment]
For the keep_alive you mean? I've not used the feature myself, but I think Martin uses HealthChecks.io I believe, as suggested [here](https://github.com/martomi/chiadog#redundant-monitoring-for-chiadog)

**Comment by BeepBo0** [comment]
> For the keep_alive you mean? I've not used the feature myself, but I believe Martin uses HealthChecks.io, as suggested [here](https://github.com/martomi/chiadog#redundant-monitoring-for-chiadog)

Awesome, many thanks!
