### ISSUE TITLE
ZeroDivisionError on daily report

### ISSUE THREAD

**Issue by rantos9** [martomi/chiadog#46]
I just update chiadog today and I set up the daily report for 3 machines, one main machine running a full node (but no local plots) and two remote harvesters. Both of the remote harvesters failed the daily report and gave out a ZeroDivisionError:

`Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/renan/chiadog/src/chia_log/handlers/daily_stats/stats_manager.py", line 87, in _run_loop
    self._send_daily_notification()
  File "/home/renan/chiadog/src/chia_log/handlers/daily_stats/stats_manager.py", line 77, in _send_daily_notification
    summary += "\n" + stat_acc.get_summary()
  File "/home/renan/chiadog/src/chia_log/handlers/daily_stats/stat_accumulators/signage_point_stats.py", line 37, in get_summary
    percentage_skipped = (self._skips_total / self._total) * 100
ZeroDivisionError: division by zero`

Chiadog is running on the full node machine.

**Comment by cbacon93** [comment]
`Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marcel/Documents/chiadog/src/chia_log/handlers/daily_stats/stats_manager.py", line 87, in _run_loop
    self._send_daily_notification()
  File "/home/marcel/Documents/chiadog/src/chia_log/handlers/daily_stats/stats_manager.py", line 77, in _send_daily_notification
    summary += "\n" + stat_acc.get_summary()
  File "/home/marcel/Documents/chiadog/src/chia_log/handlers/daily_stats/stat_accumulators/signage_point_stats.py", line 37, in get_summary
    percentage_skipped = (self._skips_total / self._total) * 100
ZeroDivisionError: division by zero`

I get the same error running on a harvester-only

**Comment by martomi** [comment]
Pushing out a new release in half hour that will fix this and few small improvements.
