### ISSUE TITLE
Failed unit tests for dateutil and yaml

### ISSUE THREAD

**Issue by chufucious** [martomi/chiadog#50]
I recently updated to the latest release `0.4` and chiadog was successfully sending notifications to Discord. Then I noticed they stopped after a while so I decided to run the unit tests.

Looks like `dateutil` and `yaml` aren't working?

I tried installing them but it didn't solve the problem.

Python `Python 2.7.16`
Pip `pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)`
```
pi@chiafarm:~/chiadog $ python3 -m unittest
EEEEEEsssINFO:root:Keep-alive check period: 3 seconds
WARNING:root:Check period below 5 minutes might result in very frequent high priority notifications in case something stops working. Is it intended?
DEBUG:root:Received keep-alive event from HARVESTER
DEBUG:root:Received keep-alive event from HARVESTER
DEBUG:root:Received keep-alive event from HARVESTER
DEBUG:root:Keep-alive check for HARVESTER: Last activity 1 seconds ago.
INFO:root:Waiting for high priority event..
INFO:root:Waiting for high priority event..
INFO:root:Waiting for high priority event..
DEBUG:root:Keep-alive check for HARVESTER: Last activity 4 seconds ago.
WARNING:root:Your harvester appears to be offline! No events for the past 4 seconds.
INFO:root:Stopping
.sssssINFO:root:Initializing script notifier.
Script notifier running with arguments: HIGH HARVESTER High priority notification 1.
.INFO:root:Initializing script notifier.
Script notifier running with arguments: LOW HARVESTER Low priority notification 1.
Script notifier running with arguments: LOW HARVESTER Low priority notification 2.
.INFO:root:Initializing script notifier.
Script notifier running with arguments: NORMAL HARVESTER Normal priority notification 1.
.sssssssssE
======================================================================
ERROR: src.chia_log.handlers (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.chia_log.handlers
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/pi/chiadog/src/chia_log/handlers/__init__.py", line 14, in <module>
    from .daily_stats.stats_manager import StatsManager
  File "/home/pi/chiadog/src/chia_log/handlers/daily_stats/__init__.py", line 5, in <module>
    from ...parsers.finished_signage_point_parser import FinishedSignagePointMessage
  File "/home/pi/chiadog/src/chia_log/parsers/finished_signage_point_parser.py", line 9, in <module>
    from dateutil import parser as dateutil_parser
ModuleNotFoundError: No module named 'dateutil'


======================================================================
ERROR: tests.chia_log.handlers.test_finished_signage_point_handler (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.chia_log.handlers.test_finished_signage_point_handler
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/pi/chiadog/tests/chia_log/handlers/test_finished_signage_point_handler.py", line 6, in <module>
    from src.chia_log.handlers import finished_signage_point_handler
  File "/home/pi/chiadog/src/chia_log/handlers/__init__.py", line 14, in <module>
    from .daily_stats.stats_manager import StatsManager
  File "/home/pi/chiadog/src/chia_log/handlers/daily_stats/__init__.py", line 5, in <module>
    from ...parsers.finished_signage_point_parser import FinishedSignagePointMessage
  File "/home/pi/chiadog/src/chia_log/parsers/finished_signage_point_parser.py", line 9, in <module>
    from dateutil import parser as dateutil_parser
ModuleNotFoundError: No module named 'dateutil'


======================================================================
ERROR: tests.chia_log.handlers.test_harvester_activity_handler (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.chia_log.handlers.test_harvester_activity_handler
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/pi/chiadog/tests/chia_log/handlers/test_harvester_activity_handler.py", line 6, in <module>
    from src.chia_log.handlers import harvester_activity_handler
  File "/home/pi/chiadog/src/chia_log/handlers/__init__.py", line 14, in <module>
    from .daily_stats.stats_manager import StatsManager
  File "/home/pi/chiadog/src/chia_log/handlers/daily_stats/__init__.py", line 5, in <module>
    from ...parsers.finished_signage_point_parser import FinishedSignagePointMessage
  File "/home/pi/chiadog/src/chia_log/parsers/finished_signage_point_parser.py", line 9, in <module>
    from dateutil import parser as dateutil_parser
ModuleNotFoundError: No module named 'dateutil'


======================================================================
ERROR: tests.chia_log.handlers.util.test_calculate_skipped_signage_points (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.chia_log.handlers.util.test_calculate_skipped_signage_points
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/pi/chiadog/tests/chia_log/handlers/util/test_calculate_skipped_signage_points.py", line 7, in <module>
    from src.chia_log.handlers.util.calculate_skipped_signage_points import calculate_skipped_signage_points
  File "/home/pi/chiadog/src/chia_log/handlers/__init__.py", line 14, in <module>
    from .daily_stats.stats_manager import StatsManager
  File "/home/pi/chiadog/src/chia_log/handlers/daily_stats/__init__.py", line 5, in <module>
    from ...parsers.finished_signage_point_parser import FinishedSignagePointMessage
  File "/home/pi/chiadog/src/chia_log/parsers/finished_signage_point_parser.py", line 9, in <module>
    from dateutil import parser as dateutil_parser
ModuleNotFoundError: No module named 'dateutil'


======================================================================
ERROR: tests.chia_log.parsers.test_finished_signage_point_parser (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.chia_log.parsers.test_finished_signage_point_parser
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/pi/chiadog/tests/chia_log/parsers/test_finished_signage_point_parser.py", line 6, in <module>
    from src.chia_log.parsers import finished_signage_point_parser
  File "/home/pi/chiadog/src/chia_log/parsers/finished_signage_point_parser.py", line 9, in <module>
    from dateutil import parser as dateutil_parser
ModuleNotFoundError: No module named 'dateutil'


======================================================================
ERROR: tests.chia_log.parsers.test_harvester_activity_parser (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.chia_log.parsers.test_harvester_activity_parser
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/pi/chiadog/tests/chia_log/parsers/test_harvester_activity_parser.py", line 6, in <module>
    from src.chia_log.parsers import harvester_activity_parser
  File "/home/pi/chiadog/src/chia_log/parsers/harvester_activity_parser.py", line 9, in <module>
    from dateutil import parser as dateutil_parser
ModuleNotFoundError: No module named 'dateutil'


======================================================================
ERROR: tests.test_config (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_config
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/pi/chiadog/tests/test_config.py", line 6, in <module>
    from src.config import Config
  File "/home/pi/chiadog/src/config.py", line 7, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'


----------------------------------------------------------------------
Ran 28 tests in 6.038s

FAILED (errors=7, skipped=17)
```

**Comment by martomi** [comment]
These are [requirements](https://github.com/martomi/chiadog/blob/main/requirements.txt) that you need to install. Described in the README. It's likely you had them installed in `venv` before but didn't activate the environment after the upgrade. In the upcoming version (already on `dev` branch) there are scripts that make this less error prone.

**Comment by martomi** [comment]
Also noticed you specified rather old version of python and pip. `chiadog` requires Python 3.7+ and pip 20+
